import type { Metadata } from 'next'
import Header from './Header'

export const metadata: Metadata = {
  title: 'Next.js13 Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body>
        <Header />
        {children}
        <footer>footer</footer>
      </body>
    </html>
  )
}
